---
- name: Copy compiled files
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/

- name: Build backend
  ignore_errors: yes
  shell: |
    tar -xvf backend.tar.gz
    cd /home/backend
    npm i
    npm run build
- name: Stop and delete already running server
  ignore_errors: yes
  shell: |
    pm2 stop backend
    pm2 delete backend
- name: Start server
  become: true
  shell: |
    cd /home/backend
    pm2 start npm --name backend -- start
    pm2 ls
