---
- name: Copy compiled files
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Install dependencies 
  ignore_errors: yes
  shell: |
    ls
    cd /home/ubuntu/backend
    npm i

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
    curl https://kvdb.io/${KVDB_BUCKET}/DEPLOY_ID  -d "testing ${WORK_ID}"